project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: true

website:
  title: "TDM Results Report"
  favicon: _pictures/favicon.ico
  page-footer:
    right: "Built using [Quarto](https://quarto.org)"
    left: |
      [![](https://wfrc.org/wp-content/uploads/2021/11/logo.jpg){fig-alt='WFRC' width=150px}](https://wfrc.org) 
      [![](https://mountainland.org/static/media/logo/svg/MAG_Logo_Horz_NoTag.svg){fig-alt='MAG' width=65px}](https://mountainland.org/)
  navbar:
    background: info
    logo: _pictures/wf-logo-new-white-t.png
    tools:
      - icon: github
        href: https://github.com/WFRCAnalytics/TDM-Documentation
    title: false
    collapse-below: lg
    left:
      - text: "Overview"
        href: index.qmd
        id: overview
      - text: "Input Processing"
        href: 0_InputProcessing/index.qmd
        id: 0-input-pro
      - text: "Trip Generation"
        href: 2_TripGen/index.qmd
        id: 2-trip-gen
      - text: "Distribution"
        href: 3_Distribute/index.qmd
        id: 3-distrib
      - text: "Mode Choice"
        href: 4_ModeChoice/index.qmd
        id: 4-mc
          
  sidebar:
    - id: 0-input-pro
      title: "Input Processing"
      contents:
        - text: "Preface"
          href: 0_InputProcessing/index.qmd
        - text: "Demographic Summary"
          href: 0_InputProcessing/demo.ipynb
        - text: "Network Processing"
          href: 0_InputProcessing/network-process.ipynb
    - id: 2-trip-gen
      title: "Trip Generation"
      contents:
        - text: "Preface"
          href: 2_TripGen/index.qmd
    - id: 3-distrib
      title: "Distribution"
      contents:
        - text: "Preface"
          href: 3_Distribute/index.qmd
    - id: 4-mc
      title: "Mode Choice"
      contents:
        - text: "Preface"
          href: 4_ModeChoice/index.qmd

format:
  html:
    toc: true
    theme:
      - cerulean
      - custom.css
    code-fold: true
  pdf:
    documentclass: scrreprt




